-- Cafeoi temel veritabanı şeması; Supabase projesinde profiles, ideas, ai_plans, templates ve usage_logs tablolarını oluşturur.
-- RLS politikaları ve edge function tetikleyicileri takip eden migration’larda eklenecektir.

create table if not exists public.profiles (
    id uuid primary key default gen_random_uuid(),
    email text unique not null,
    full_name text,
    plan text not null default 'free',
    billing_status text default 'inactive',
    created_at timestamptz not null default now()
);

create table if not exists public.ideas (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.profiles (id) on delete cascade,
    problem text not null,
    target_user text not null,
    solution text not null,
    status text not null default 'draft',
    created_at timestamptz not null default now()
);

create table if not exists public.ai_plans (
    id bigint generated by default as identity primary key,
    idea_id bigint not null references public.ideas (id) on delete cascade,
    summary text not null,
    architecture jsonb not null,
    database_schema jsonb not null,
    roadmap jsonb not null,
    export_options jsonb not null,
    created_at timestamptz not null default now()
);

create table if not exists public.templates (
    id bigint generated by default as identity primary key,
    slug text unique not null,
    name text not null,
    description text,
    access_level text not null default 'free',
    assets_url text,
    created_at timestamptz not null default now()
);

create table if not exists public.usage_logs (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.profiles (id) on delete cascade,
    action text not null,
    metadata jsonb,
    occurred_at timestamptz not null default now()
);

create table if not exists public.payments (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.profiles (id) on delete cascade,
    provider text not null,
    amount numeric(10,2) not null,
    currency text not null default 'USD',
    status text not null,
    invoice_url text,
    created_at timestamptz not null default now()
);
